plugins:
  - node
  - promise
  - standard
  - unicorn
  - prettier

extends:
  - eslint:recommended
  - plugin:unicorn/recommended
  - plugin:node/recommended
  - xo/esnext
  - prettier

env:
  es6: true

parserOptions:
  sourceType: script
  ecmaVersion: 2017

rules:
  strict: [error, global]
  semi: [error, never]
  comma-dangle: [error, always-multiline]
  indent: [error, 2]
  no-multi-assign: 0
  func-names: 0
  operator-linebreak: [error, after, {overrides: {"?": before, ":": "before" } }]
  capitalized-comments: [error, always, {ignorePattern: prettier-ignore, ignoreConsecutiveComments: true}]
  # ES2015 http://eslint.org/docs/rules/#ecmascript-6
  prefer-rest-params: [error]
  prefer-spread: [error]
  prefer-destructuring: [error]
  # node https://github.com/mysticatea/eslint-plugin-node
  node/no-unpublished-require: 0 # doesn't play nice with monorepo
  node/no-extraneous-require: [error, allowModules: [ava, sinon, "@xmpp/test"]]
  node/no-unsupported-features/es-syntax: [error]
  node/no-unsupported-features/es-builtins: [error]
  # standard https://github.com/xjamundx/eslint-plugin-standard
  standard/no-callback-literal: [error, [cb, callback]]
  # unicorn https://github.com/sindresorhus/eslint-plugin-unicorn
  unicorn/filename-case: 0
  unicorn/catch-error-name: [2, {name: "err"}]
